spring.datasource.url=jdbc:postgresql://localhost:5432/userdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=validate
jwt.secret=MallManagementSystemSecretKeyForJWTTokenGenerationMustBeAtLeast256Bits
jwt.expiration=86400000
