spring.application.name=employee-operations-service
server.port=8086
spring.config.import=optional:configserver:http://localhost:8888
mongock.migration-scan-package=com.mall.employeeoperations.changelog
