server.port=8083
spring.application.name=product-catalog-service

# MongoDB configuration
spring.data.mongodb.uri=mongodb://localhost:27017/productdb

jwt.secret=MallManagementSystemSecretKeyForJWTTokenGenerationMustBeAtLeast256Bits
